In [211]:
import pandas as pd
import numpy as np
import calendar

In [212]:
df = pd.read_csv('Retail Canada.csv')
df.head(10)

,REF_DATE,GEO,DGUID,Products,UOM,UOM_ID,SCALAR_FACTOR,SCALAR_ID,VECTOR,COORDINATE,VALUE,STATUS,SYMBOL,TERMINATED,DECIMALS
0,2017-01,Canada,2016A000011124,"Beef stewing cuts, per kilogram",Dollars,81,units,0,v1353834271,11.10,12.66,NaN,NaN,NaN,2
1,2017-01,Canada,2016A000011124,"Beef striploin cuts, per kilogram",Dollars,81,units,0,v1353834272,11.20,21.94,NaN,NaN,NaN,2
2,2017-01,Canada,2016A000011124,"Beef top sirloin cuts, per kilogram",Dollars,81,units,0,v1353834273,11.30,13.44,NaN,NaN,NaN,2
3,2017-01,Canada,2016A000011124,"Beef rib cuts, per kilogram",Dollars,81,units,0,v1353834311,11.41,20.17,NaN,NaN,NaN,2
4,2017-01,Canada,2016A000011124,"Ground beef, per kilogram",Dollars,81,units,0,v1353834274,11.40,9.12,NaN,NaN,NaN,2
5,2017-01,Canada,2016A000011124,"Pork loin cuts, per kilogram",Dollars,81,units,0,v1353834275,11.50,7.34,NaN,NaN,NaN,2
6,2017-01,Canada,2016A000011124,"Pork rib cuts, per kilogram",Dollars,81,units,0,v1353834276,11.60,7.37,NaN,NaN,NaN,2
7,2017-01,Canada,2016A000011124,"Pork shoulder cuts, per kilogram",Dollars,81,units,0,v1353834312,11.42,4.76,NaN,NaN,NaN,2
8,2017-01,Canada,2016A000011124,"Whole chicken, per kilogram",Dollars,81,units,0,v1353834277,11.70,5.15,NaN,NaN,NaN,2
9,2017-01,Canada,2016A000011124,"Chicken breasts, per kilogram",Dollars,81,units,0,v1353834278,11.80,11.38,NaN,NaN,NaN,2

In [213]:
df.columns

Index(['REF_DATE', 'GEO', 'DGUID', 'Products', 'UOM', 'UOM_ID',
       'SCALAR_FACTOR', 'SCALAR_ID', 'VECTOR', 'COORDINATE', 'VALUE', 'STATUS',
       'SYMBOL', 'TERMINATED', 'DECIMALS'],
      dtype='object')

In [214]:
df = df[['REF_DATE', 'GEO', 'Products', 'VALUE','UOM' ]]
df.head(10)

  REF_DATE     GEO                             Products  VALUE      UOM
0  2017-01  Canada      Beef stewing cuts, per kilogram  12.66  Dollars
1  2017-01  Canada    Beef striploin cuts, per kilogram  21.94  Dollars
2  2017-01  Canada  Beef top sirloin cuts, per kilogram  13.44  Dollars
3  2017-01  Canada          Beef rib cuts, per kilogram  20.17  Dollars
4  2017-01  Canada            Ground beef, per kilogram   9.12  Dollars
5  2017-01  Canada         Pork loin cuts, per kilogram   7.34  Dollars
6  2017-01  Canada          Pork rib cuts, per kilogram   7.37  Dollars
7  2017-01  Canada     Pork shoulder cuts, per kilogram   4.76  Dollars
8  2017-01  Canada          Whole chicken, per kilogram   5.15  Dollars
9  2017-01  Canada        Chicken breasts, per kilogram  11.38  Dollars

In [215]:
df.isnull().values.any()

False

In [216]:
df= df.rename(columns = {'GEO' : 'Location'})
df.dtypes

REF_DATE     object
Location     object
Products     object
VALUE       float64
UOM          object
dtype: object

In [217]:
df['Products Name'] = df['Products'].astype('string').str.split(',').str[0]

df['Amount'] = df['Products'].astype('string').str.split(',').str[1]

df.sample(10)

,REF_DATE,Location,Products,VALUE,UOM,Products Name,Amount
24541,2018-09,Nova Scotia,"Oranges, 1.36 kilograms",4.72,Dollars,Oranges,1.36 kilograms
97796,2023-09,Alberta,"Peanut butter, 1 kilogram",6.27,Dollars,Peanut butter,1 kilogram
61212,2021-03,Ontario,"Almonds, 200 grams",4.83,Dollars,Almonds,200 grams
54268,2020-09,Alberta,"Canola oil, 3 litres",6.40,Dollars,Canola oil,3 litres
30135,2019-01,British Columbia,"Milk, 2 litres",4.09,Dollars,Milk,2 litres
7193,2017-06,British Columbia,"Celery, unit",2.81,Dollars,Celery,unit
97087,2023-09,Nova Scotia,"Cantaloupe, unit",3.85,Dollars,Cantaloupe,unit
41544,2019-11,Nova Scotia,"Laundry detergent, 4.43 litres",11.82,Dollars,Laundry detergent,4.43 litres
91693,2023-04,Alberta,"Eggs, 1 dozen",4.76,Dollars,Eggs,1 dozen
44434,2020-01,Saskatchewan,"Oranges, per kilogram",3.17,Dollars,Oranges,per kilogram

In [218]:
df['Quantity'] = df['Amount'].astype('string').str.replace('per', '1')
df.sample(10)

,REF_DATE,Location,Products,VALUE,UOM,Products Name,Amount,Quantity
12846,2017-11,Ontario,"Dry beans and legumes, 900 grams",2.69,Dollars,Dry beans and legumes,900 grams,900 grams
78086,2022-05,Ontario,"Mushrooms, 227 grams",2.59,Dollars,Mushrooms,227 grams,227 grams
11079,2017-10,Newfoundland and Labrador,"Canned baked beans, 398 millilitres",1.34,Dollars,Canned baked beans,398 millilitres,398 millilitres
85827,2022-11,British Columbia,"Tofu, 350 grams",3.01,Dollars,Tofu,350 grams,350 grams
80081,2022-07,Prince Edward Island,"Flatbread and pita, 500 grams",4.15,Dollars,Flatbread and pita,500 grams,500 grams
83113,2022-09,Saskatchewan,"Soy milk, 1.89 litres",4.10,Dollars,Soy milk,1.89 litres,1.89 litres
54443,2020-10,Canada,"Cantaloupe, unit",3.74,Dollars,Cantaloupe,unit,unit
42851,2019-12,New Brunswick,"Dry beans and legumes, 900 grams",3.57,Dollars,Dry beans and legumes,900 grams,900 grams
98854,2023-10,Saskatchewan,"Carrots, 1.36 kilograms",4.47,Dollars,Carrots,1.36 kilograms,1.36 kilograms
77307,2022-04,British Columbia,"Potatoes, 4.54 kilograms",6.38,Dollars,Potatoes,4.54 kilograms,4.54 kilograms

In [219]:
df['Year'] = df['REF_DATE'].astype('string').str.split('-').str[0]
df['Month'] = df['REF_DATE'].astype('string').str.split('-').str[1]
df.sample(10)

,REF_DATE,Location,Products,VALUE,UOM,Products Name,Amount,Quantity,Year,Month
23081,2018-08,Newfoundland and Labrador,"Beef stewing cuts, per kilogram",14.82,Dollars,Beef stewing cuts,per kilogram,1 kilogram,2018,08
82056,2022-08,Alberta,"Frozen pizza, 390 grams",4.27,Dollars,Frozen pizza,390 grams,390 grams,2022,08
64893,2021-06,Manitoba,"Onions, per kilogram",4.01,Dollars,Onions,per kilogram,1 kilogram,2021,06
67464,2021-08,Saskatchewan,"Canned tomatoes, 796 millilitres",1.50,Dollars,Canned tomatoes,796 millilitres,796 millilitres,2021,08
77612,2022-05,Prince Edward Island,"Canned tuna, 170 grams",2.25,Dollars,Canned tuna,170 grams,170 grams,2022,05
93304,2023-06,Newfoundland and Labrador,"Salad dressing, 475 millilitres",3.47,Dollars,Salad dressing,475 millilitres,475 millilitres,2023,06
1246,2017-02,Canada,"Grapes, per kilogram",5.85,Dollars,Grapes,per kilogram,1 kilogram,2017,02
73244,2022-01,Ontario,"Cabbage, per kilogram",2.24,Dollars,Cabbage,per kilogram,1 kilogram,2022,01
88176,2023-01,British Columbia,"Eggs, 1 dozen",5.22,Dollars,Eggs,1 dozen,1 dozen,2023,01
14313,2017-12,Alberta,"Butter, 454 grams",4.01,Dollars,Butter,454 grams,454 grams,2017,12

In [220]:
df_check = df.loc[df['Products Name']=='Milk']
df_check.sample(10)

,REF_DATE,Location,Products,VALUE,UOM,Products Name,Amount,Quantity,Year,Month
102016,2024-01,New Brunswick,"Milk, 4 litres",8.28,Dollars,Milk,4 litres,4 litres,2024,01
2218,2017-02,Alberta,"Milk, 2 litres",3.90,Dollars,Milk,2 litres,2 litres,2017,02
62449,2021-04,Manitoba,"Milk, 4 litres",4.89,Dollars,Milk,4 litres,4 litres,2021,04
92784,2023-05,Saskatchewan,"Milk, 4 litres",5.69,Dollars,Milk,4 litres,4 litres,2023,05
34202,2019-05,Nova Scotia,"Milk, 4 litres",5.62,Dollars,Milk,4 litres,4 litres,2019,05
2329,2017-02,British Columbia,"Milk, 4 litres",4.82,Dollars,Milk,4 litres,4 litres,2017,02
41126,2019-11,Canada,"Milk, 2 litres",4.19,Dollars,Milk,2 litres,2 litres,2019,11
27826,2018-12,Canada,"Milk, 1 litre",2.48,Dollars,Milk,1 litre,1 litre,2018,12
58821,2021-01,Manitoba,"Milk, 2 litres",3.73,Dollars,Milk,2 litres,2 litres,2021,01
10130,2017-09,New Brunswick,"Milk, 1 litre",2.25,Dollars,Milk,1 litre,1 litre,2017,09

In [221]:
df['Month'] = df['Month'].astype(int).apply(lambda x: calendar.month_abbr[x])

In [222]:
df.dtypes

REF_DATE                 object
Location                 object
Products                 object
VALUE                   float64
UOM                      object
Products Name            object
Amount                   object
Quantity         string[python]
Year                     object
Month                    object
dtype: object

In [223]:
unique_products = df['Products Name'].unique()
print(unique_products)
print(len(unique_products))

['Beef stewing cuts' 'Beef striploin cuts' 'Beef top sirloin cuts'
 'Beef rib cuts' 'Ground beef' 'Pork loin cuts' 'Pork rib cuts'
 'Pork shoulder cuts' 'Whole chicken' 'Chicken breasts' 'Chicken thigh'
 'Chicken drumsticks' 'Bacon' 'Wieners' 'Salmon' 'Shrimp' 'Canned salmon'
 'Canned tuna' 'Meatless burgers' 'Milk' 'Soy milk' 'Nut milk' 'Cream'
 'Butter' 'Margarine' 'Block cheese' 'Yogurt' 'Eggs' 'Apples' 'Oranges'
 'Bananas' 'Pears' 'Lemons' 'Limes' 'Grapes' 'Cantaloupe' 'Strawberries'
 'Avocado' 'Potatoes' 'Sweet potatoes' 'Tomatoes' 'Cabbage' 'Carrots'
 'Onions' 'Celery' 'Cucumber' 'Mushrooms' 'Iceberg lettuce'
 'Romaine lettuce' 'Broccoli' 'Peppers' 'Squash' 'Salad greens'
 'Frozen french fried potatoes' 'Frozen green beans' 'Frozen broccoli'
 'Frozen corn' 'Frozen mixed vegetables' 'Frozen peas' 'Frozen pizza'
 'Frozen spinach' 'Frozen strawberries' 'White bread' 'Flatbread and pita'
 'Crackers and crisp breads' 'Cookies and sweet biscuits'
 'Dry or fresh pasta' 'Brown rice' 'White rice' 'Cereal' 'Wheat flour'
 'White sugar' 'Apple juice' 'Orange juice' 'Roasted or ground coffee'
 'Tea (20 bags)' 'Ketchup' 'Vegetable oil' 'Canola oil' 'Olive oil'
 'Baby food' 'Infant formula' 'Peanut butter' 'Mayonnaise'
 'Canned baked beans' 'Canned tomatoes' 'Canned soup'
 'Canned beans and lentils' 'Canned corn' 'Canned peach' 'Canned pear'
 'Dried lentils' 'Dry beans and legumes' 'Tofu' 'Hummus' 'Salsa'
 'Pasta sauce' 'Salad dressing' 'Almonds' 'Peanuts' 'Sunflower seeds'
 'Deodorant' 'Toothpaste' 'Shampoo' 'Laundry detergent']
105

In [224]:
# define conditions
conditions =[
df['Products Name'].isin(['Beef stewing cuts' ,'Beef striploin cuts' ,'Beef top sirloin cuts',
 'Beef rib cuts', 'Ground beef' ,'Pork loin cuts', 'Pork rib cuts',
 'Pork shoulder cuts' ,'Whole chicken', 'Chicken breasts', 'Chicken thigh',
 'Chicken drumsticks', 'Bacon' ,'Wieners', 'Salmon' ,'Shrimp' ,'Canned salmon',
 'Canned tuna' ,'Meatless burgers']) ,

df['Products Name'].isin(['Milk' ,'Soy milk' ,'Nut milk' ,'Cream',
 'Butter', 'Margarine', 'Block cheese' ,'Yogurt', 'Eggs']),

df['Products Name'].isin(['Apples' ,'Oranges',
 'Bananas' ,'Pears', 'Lemons', 'Limes', 'Grapes' ,'Cantaloupe', 'Strawberries',
 'Avocado', 'Potatoes', 'Sweet potatoes', 'Tomatoes', 'Cabbage' ,'Carrots',
 'Onions' ,'Celery' ,'Cucumber', 'Mushrooms', 'Iceberg lettuce',
 'Romaine lettuce', 'Broccoli', 'Peppers' ,'Squash', 'Salad greens',
 'Frozen french fried potatoes', 'Frozen green beans', 'Frozen broccoli',
 'Frozen corn' ,'Frozen mixed vegetables', 'Frozen peas' ,'Frozen pizza',
 'Frozen spinach', 'Frozen strawberries' ]),

df['Products Name'].isin(['White bread','Flatbread and pita',
 'Crackers and crisp breads', 'Cookies and sweet biscuits',
 'Dry or fresh pasta', 'Brown rice' ,'White rice' ,'Cereal' ,'Wheat flour',
 'White sugar' ,'Apple juice' ,'Orange juice', 'Roasted or ground coffee',
 'Tea (20 bags)', 'Ketchup', 'Vegetable oil' ,'Canola oil' ,'Olive oil',
 'Peanut butter', 'Mayonnaise','Canned baked beans' ,'Canned tomatoes', 'Canned soup',
 'Canned beans and lentils', 'Canned corn' ,'Canned peach', 'Canned pear',
 'Dried lentils', 'Dry beans and legumes', 'Tofu', 'Hummus', 'Salsa',
 'Pasta sauce', 'Salad dressing', 'Almonds' ,'Peanuts' ,'Sunflower seeds']),

df['Products Name'].isin(['Deodorant', 'Toothpaste', 'Shampoo' ,'Laundry detergent','Baby food' , 'Infant formula'])

]

# define results
results = ['Meat & Seafood', 'Dairy & Eggs', 'Fruits & Vegetables','Pantry','Home,Beauty & Baby']

df['Category'] = np.select(conditions,results)

In [225]:
df.sample(10)

,REF_DATE,Location,Products,VALUE,UOM,Products Name,Amount,Quantity,Year,Month,Category
57554,2020-12,Ontario,"Brown rice, 900 grams",4.88,Dollars,Brown rice,900 grams,900 grams,2020,Dec,Pantry
104709,2024-03,Ontario,"White sugar, 2 kilograms",2.60,Dollars,White sugar,2 kilograms,2 kilograms,2024,Mar,Pantry
98473,2023-10,New Brunswick,"Sunflower seeds, 400 grams",5.19,Dollars,Sunflower seeds,400 grams,400 grams,2023,Oct,Pantry
5206,2017-05,Nova Scotia,"Potatoes, 4.54 kilograms",3.85,Dollars,Potatoes,4.54 kilograms,4.54 kilograms,2017,May,Fruits & Vegetables
73172,2022-01,Quebec,"Canola oil, 3 litres",10.23,Dollars,Canola oil,3 litres,3 litres,2022,Jan,Pantry
64091,2021-06,Canada,"Salmon, per kilogram",24.27,Dollars,Salmon,per kilogram,1 kilogram,2021,Jun,Meat & Seafood
103417,2024-02,Quebec,"Almonds, 200 grams",5.24,Dollars,Almonds,200 grams,200 grams,2024,Feb,Pantry
83230,2022-09,Alberta,"Eggs, 1 dozen",4.65,Dollars,Eggs,1 dozen,1 dozen,2022,Sep,Dairy & Eggs
77787,2022-05,Nova Scotia,"Vegetable oil, 3 litres",12.18,Dollars,Vegetable oil,3 litres,3 litres,2022,May,Pantry
59954,2021-02,Ontario,"Broccoli, unit",2.14,Dollars,Broccoli,unit,unit,2021,Feb,Fruits & Vegetables

In [226]:
df.columns

Index(['REF_DATE', 'Location', 'Products', 'VALUE', 'UOM', 'Products Name',
       'Amount', 'Quantity', 'Year', 'Month', 'Category'],
      dtype='object')

In [227]:
df = df[['Year', 'Month','Location','Products Name','Quantity','Category','VALUE']]

In [228]:
df.sample(10)

,Year,Month,Location,Products Name,Quantity,Category,VALUE
100920,2023,Dec,Quebec,Cream,1 litre,Dairy & Eggs,3.93
54918,2020,Oct,New Brunswick,Cereal,400 grams,Pantry,3.31
92093,2023,May,Newfoundland and Labrador,Salsa,418 millilitres,Pantry,4.80
62454,2021,Apr,Manitoba,Margarine,907 grams,Dairy & Eggs,4.20
23669,2018,Aug,Ontario,Strawberries,454 grams,Fruits & Vegetables,2.81
24287,2018,Sep,Canada,Toothpaste,100 millilitres,"Home,Beauty & Baby",2.83
37391,2019,Jul,British Columbia,Soy milk,1.89 litres,Dairy & Eggs,3.85
71471,2021,Dec,Newfoundland and Labrador,Oranges,1 kilogram,Fruits & Vegetables,5.31
19635,2018,May,Prince Edward Island,Brown rice,900 grams,Pantry,4.93
2962,2017,Mar,New Brunswick,Sunflower seeds,400 grams,Pantry,4.18