In [4]:
import pandas as pd
import numpy as np
import calendar

In [5]:
df = pd.read_csv('Retail Canada.csv')
df.head(10)

,REF_DATE,GEO,DGUID,Products,UOM,UOM_ID,SCALAR_FACTOR,SCALAR_ID,VECTOR,COORDINATE,VALUE,STATUS,SYMBOL,TERMINATED,DECIMALS
0,2017-01,Canada,2016A000011124,"Beef stewing cuts, per kilogram",Dollars,81,units,0,v1353834271,11.10,12.66,NaN,NaN,NaN,2
1,2017-01,Canada,2016A000011124,"Beef striploin cuts, per kilogram",Dollars,81,units,0,v1353834272,11.20,21.94,NaN,NaN,NaN,2
2,2017-01,Canada,2016A000011124,"Beef top sirloin cuts, per kilogram",Dollars,81,units,0,v1353834273,11.30,13.44,NaN,NaN,NaN,2
3,2017-01,Canada,2016A000011124,"Beef rib cuts, per kilogram",Dollars,81,units,0,v1353834311,11.41,20.17,NaN,NaN,NaN,2
4,2017-01,Canada,2016A000011124,"Ground beef, per kilogram",Dollars,81,units,0,v1353834274,11.40,9.12,NaN,NaN,NaN,2
5,2017-01,Canada,2016A000011124,"Pork loin cuts, per kilogram",Dollars,81,units,0,v1353834275,11.50,7.34,NaN,NaN,NaN,2
6,2017-01,Canada,2016A000011124,"Pork rib cuts, per kilogram",Dollars,81,units,0,v1353834276,11.60,7.37,NaN,NaN,NaN,2
7,2017-01,Canada,2016A000011124,"Pork shoulder cuts, per kilogram",Dollars,81,units,0,v1353834312,11.42,4.76,NaN,NaN,NaN,2
8,2017-01,Canada,2016A000011124,"Whole chicken, per kilogram",Dollars,81,units,0,v1353834277,11.70,5.15,NaN,NaN,NaN,2
9,2017-01,Canada,2016A000011124,"Chicken breasts, per kilogram",Dollars,81,units,0,v1353834278,11.80,11.38,NaN,NaN,NaN,2

In [6]:
df.columns

Index(['REF_DATE', 'GEO', 'DGUID', 'Products', 'UOM', 'UOM_ID',
       'SCALAR_FACTOR', 'SCALAR_ID', 'VECTOR', 'COORDINATE', 'VALUE', 'STATUS',
       'SYMBOL', 'TERMINATED', 'DECIMALS'],
      dtype='object')

In [7]:
df = df[['REF_DATE', 'GEO', 'Products', 'VALUE','UOM' ]]
df.head(10)

  REF_DATE     GEO                             Products  VALUE      UOM
0  2017-01  Canada      Beef stewing cuts, per kilogram  12.66  Dollars
1  2017-01  Canada    Beef striploin cuts, per kilogram  21.94  Dollars
2  2017-01  Canada  Beef top sirloin cuts, per kilogram  13.44  Dollars
3  2017-01  Canada          Beef rib cuts, per kilogram  20.17  Dollars
4  2017-01  Canada            Ground beef, per kilogram   9.12  Dollars
5  2017-01  Canada         Pork loin cuts, per kilogram   7.34  Dollars
6  2017-01  Canada          Pork rib cuts, per kilogram   7.37  Dollars
7  2017-01  Canada     Pork shoulder cuts, per kilogram   4.76  Dollars
8  2017-01  Canada          Whole chicken, per kilogram   5.15  Dollars
9  2017-01  Canada        Chicken breasts, per kilogram  11.38  Dollars

In [8]:
df.isnull().values.any()

False

In [9]:
df= df.rename(columns = {'GEO' : 'Location'})
df.dtypes

REF_DATE     object
Location     object
Products     object
VALUE       float64
UOM          object
dtype: object

In [10]:
df['Products Name'] = df['Products'].astype('string').str.split(',').str[0]

df['Amount'] = df['Products'].astype('string').str.split(',').str[1]

df.sample(10)

,REF_DATE,Location,Products,VALUE,UOM,Products Name,Amount
67237,2021-08,Ontario,"Canola oil, 3 litres",8.68,Dollars,Canola oil,3 litres
93790,2023-06,Ontario,"Cantaloupe, unit",3.67,Dollars,Cantaloupe,unit
35035,2019-05,British Columbia,"Olive oil, 1 litre",8.81,Dollars,Olive oil,1 litre
104813,2024-03,Manitoba,"Cookies and sweet biscuits, 300 grams",3.18,Dollars,Cookies and sweet biscuits,300 grams
77312,2022-04,British Columbia,"Carrots, 1.36 kilograms",4.95,Dollars,Carrots,1.36 kilograms
25064,2018-09,Saskatchewan,"Pork loin cuts, per kilogram",9.44,Dollars,Pork loin cuts,per kilogram
65281,2021-06,British Columbia,"Sunflower seeds, 400 grams",3.97,Dollars,Sunflower seeds,400 grams
63249,2021-05,Nova Scotia,"Iceberg lettuce, unit",2.81,Dollars,Iceberg lettuce,unit
83781,2022-10,Nova Scotia,"Oranges, per kilogram",5.24,Dollars,Oranges,per kilogram
53662,2020-09,New Brunswick,"Block cheese, 500 grams",6.14,Dollars,Block cheese,500 grams

In [11]:
df['Quantity'] = df['Amount'].astype('string').str.replace('per', '1')
df.sample(10)

,REF_DATE,Location,Products,VALUE,UOM,Products Name,Amount,Quantity
5726,2017-05,Saskatchewan,"Chicken drumsticks, per kilogram",6.35,Dollars,Chicken drumsticks,per kilogram,1 kilogram
43435,2019-12,British Columbia,"Milk, 4 litres",4.82,Dollars,Milk,4 litres,4 litres
17156,2018-03,Prince Edward Island,"Chicken drumsticks, per kilogram",5.06,Dollars,Chicken drumsticks,per kilogram,1 kilogram
91417,2023-04,Ontario,"Canola oil, 3 litres",14.07,Dollars,Canola oil,3 litres,3 litres
17592,2018-03,Ontario,"Pork shoulder cuts, per kilogram",6.64,Dollars,Pork shoulder cuts,per kilogram,1 kilogram
97164,2023-09,New Brunswick,"Pork loin cuts, per kilogram",9.71,Dollars,Pork loin cuts,per kilogram,1 kilogram
19650,2018-05,Prince Edward Island,"Peanut butter, 1 kilogram",4.38,Dollars,Peanut butter,1 kilogram,1 kilogram
46256,2020-03,Prince Edward Island,"Canned pear, 398 millilitres",2.48,Dollars,Canned pear,398 millilitres,398 millilitres
89340,2023-02,Alberta,"Canned peach, 398 millilitres",2.86,Dollars,Canned peach,398 millilitres,398 millilitres
62728,2021-04,Alberta,Tea (20 bags),3.92,Dollars,Tea (20 bags),NaN,<NA>

In [12]:
df['Year'] = df['REF_DATE'].astype('string').str.split('-').str[0]
df['Month'] = df['REF_DATE'].astype('string').str.split('-').str[1]
df.sample(10)

,REF_DATE,Location,Products,VALUE,UOM,Products Name,Amount,Quantity,Year,Month
98961,2023-10,Alberta,"Sweet potatoes, per kilogram",3.08,Dollars,Sweet potatoes,per kilogram,1 kilogram,2023,10
4803,2017-04,British Columbia,"Apple juice, 2 litres",2.81,Dollars,Apple juice,2 litres,2 litres,2017,04
101371,2023-12,Alberta,"Lemons, unit",1.00,Dollars,Lemons,unit,unit,2023,12
29996,2019-01,Saskatchewan,"Pasta sauce, 650 millilitres",2.07,Dollars,Pasta sauce,650 millilitres,650 millilitres,2019,01
94830,2023-07,New Brunswick,"Canned baked beans, 398 millilitres",1.93,Dollars,Canned baked beans,398 millilitres,398 millilitres,2023,07
28110,2018-12,Prince Edward Island,"Olive oil, 1 litre",7.03,Dollars,Olive oil,1 litre,1 litre,2018,12
14090,2017-12,Manitoba,"Soy milk, 1.89 litres",3.85,Dollars,Soy milk,1.89 litres,1.89 litres,2017,12
32512,2019-03,Alberta,"Canned baked beans, 398 millilitres",1.34,Dollars,Canned baked beans,398 millilitres,398 millilitres,2019,03
40443,2019-10,New Brunswick,"Toothpaste, 100 millilitres",3.34,Dollars,Toothpaste,100 millilitres,100 millilitres,2019,10
49174,2020-05,Manitoba,"Cabbage, per kilogram",2.53,Dollars,Cabbage,per kilogram,1 kilogram,2020,05

In [13]:
df_check = df.loc[df['Products Name']=='Milk']
df_check.sample(10)

,REF_DATE,Location,Products,VALUE,UOM,Products Name,Amount,Quantity,Year,Month
51238,2020-07,New Brunswick,"Milk, 4 litres",7.12,Dollars,Milk,4 litres,4 litres,2020,07
26508,2018-10,British Columbia,"Milk, 2 litres",4.06,Dollars,Milk,2 litres,2 litres,2018,10
100695,2023-12,Nova Scotia,"Milk, 1 litre",2.97,Dollars,Milk,1 litre,1 litre,2023,12
50138,2020-06,Quebec,"Milk, 2 litres",4.46,Dollars,Milk,2 litres,2 litres,2020,06
57721,2020-12,Saskatchewan,"Milk, 1 litre",2.51,Dollars,Milk,1 litre,1 litre,2020,12
70141,2021-11,Canada,"Milk, 1 litre",2.63,Dollars,Milk,1 litre,1 litre,2021,11
99708,2023-11,Quebec,"Milk, 4 litres",7.83,Dollars,Milk,4 litres,4 litres,2023,11
61128,2021-03,Ontario,"Milk, 1 litre",3.28,Dollars,Milk,1 litre,1 litre,2021,03
31893,2019-03,New Brunswick,"Milk, 2 litres",3.81,Dollars,Milk,2 litres,2 litres,2019,03
52007,2020-08,Canada,"Milk, 2 litres",4.35,Dollars,Milk,2 litres,2 litres,2020,08

In [14]:
df['Month'] = df['Month'].astype(int).apply(lambda x: calendar.month_abbr[x])

In [15]:
df.dtypes

REF_DATE                 object
Location                 object
Products                 object
VALUE                   float64
UOM                      object
Products Name            object
Amount                   object
Quantity         string[python]
Year                     object
Month                    object
dtype: object

In [16]:
unique_products = df['Products Name'].unique()
print(unique_products)
print(len(unique_products))

['Beef stewing cuts' 'Beef striploin cuts' 'Beef top sirloin cuts'
 'Beef rib cuts' 'Ground beef' 'Pork loin cuts' 'Pork rib cuts'
 'Pork shoulder cuts' 'Whole chicken' 'Chicken breasts' 'Chicken thigh'
 'Chicken drumsticks' 'Bacon' 'Wieners' 'Salmon' 'Shrimp' 'Canned salmon'
 'Canned tuna' 'Meatless burgers' 'Milk' 'Soy milk' 'Nut milk' 'Cream'
 'Butter' 'Margarine' 'Block cheese' 'Yogurt' 'Eggs' 'Apples' 'Oranges'
 'Bananas' 'Pears' 'Lemons' 'Limes' 'Grapes' 'Cantaloupe' 'Strawberries'
 'Avocado' 'Potatoes' 'Sweet potatoes' 'Tomatoes' 'Cabbage' 'Carrots'
 'Onions' 'Celery' 'Cucumber' 'Mushrooms' 'Iceberg lettuce'
 'Romaine lettuce' 'Broccoli' 'Peppers' 'Squash' 'Salad greens'
 'Frozen french fried potatoes' 'Frozen green beans' 'Frozen broccoli'
 'Frozen corn' 'Frozen mixed vegetables' 'Frozen peas' 'Frozen pizza'
 'Frozen spinach' 'Frozen strawberries' 'White bread' 'Flatbread and pita'
 'Crackers and crisp breads' 'Cookies and sweet biscuits'
 'Dry or fresh pasta' 'Brown rice' 'White rice' 'Cereal' 'Wheat flour'
 'White sugar' 'Apple juice' 'Orange juice' 'Roasted or ground coffee'
 'Tea (20 bags)' 'Ketchup' 'Vegetable oil' 'Canola oil' 'Olive oil'
 'Baby food' 'Infant formula' 'Peanut butter' 'Mayonnaise'
 'Canned baked beans' 'Canned tomatoes' 'Canned soup'
 'Canned beans and lentils' 'Canned corn' 'Canned peach' 'Canned pear'
 'Dried lentils' 'Dry beans and legumes' 'Tofu' 'Hummus' 'Salsa'
 'Pasta sauce' 'Salad dressing' 'Almonds' 'Peanuts' 'Sunflower seeds'
 'Deodorant' 'Toothpaste' 'Shampoo' 'Laundry detergent']
105

In [17]:
# define conditions
conditions =[
df['Products Name'].isin(['Beef stewing cuts' ,'Beef striploin cuts' ,'Beef top sirloin cuts',
 'Beef rib cuts', 'Ground beef' ,'Pork loin cuts', 'Pork rib cuts',
 'Pork shoulder cuts' ,'Whole chicken', 'Chicken breasts', 'Chicken thigh',
 'Chicken drumsticks', 'Bacon' ,'Wieners', 'Salmon' ,'Shrimp' ,'Canned salmon',
 'Canned tuna' ,'Meatless burgers']) ,

df['Products Name'].isin(['Milk' ,'Soy milk' ,'Nut milk' ,'Cream',
 'Butter', 'Margarine', 'Block cheese' ,'Yogurt', 'Eggs']),

df['Products Name'].isin(['Apples' ,'Oranges',
 'Bananas' ,'Pears', 'Lemons', 'Limes', 'Grapes' ,'Cantaloupe', 'Strawberries',
 'Avocado', 'Potatoes', 'Sweet potatoes', 'Tomatoes', 'Cabbage' ,'Carrots',
 'Onions' ,'Celery' ,'Cucumber', 'Mushrooms', 'Iceberg lettuce',
 'Romaine lettuce', 'Broccoli', 'Peppers' ,'Squash', 'Salad greens',
 'Frozen french fried potatoes', 'Frozen green beans', 'Frozen broccoli',
 'Frozen corn' ,'Frozen mixed vegetables', 'Frozen peas' ,'Frozen pizza',
 'Frozen spinach', 'Frozen strawberries' ]),

df['Products Name'].isin(['White bread','Flatbread and pita',
 'Crackers and crisp breads', 'Cookies and sweet biscuits',
 'Dry or fresh pasta', 'Brown rice' ,'White rice' ,'Cereal' ,'Wheat flour',
 'White sugar' ,'Apple juice' ,'Orange juice', 'Roasted or ground coffee',
 'Tea (20 bags)', 'Ketchup', 'Vegetable oil' ,'Canola oil' ,'Olive oil',
 'Peanut butter', 'Mayonnaise','Canned baked beans' ,'Canned tomatoes', 'Canned soup',
 'Canned beans and lentils', 'Canned corn' ,'Canned peach', 'Canned pear',
 'Dried lentils', 'Dry beans and legumes', 'Tofu', 'Hummus', 'Salsa',
 'Pasta sauce', 'Salad dressing', 'Almonds' ,'Peanuts' ,'Sunflower seeds']),

df['Products Name'].isin(['Deodorant', 'Toothpaste', 'Shampoo' ,'Laundry detergent','Baby food' , 'Infant formula'])

]

# define results
results = ['Meat & Seafood', 'Dairy & Eggs', 'Fruits & Vegetables','Pantry','Home,Beauty & Baby']

df['Category'] = np.select(conditions,results)

In [18]:
df.sample(10)

,REF_DATE,Location,Products,VALUE,UOM,Products Name,Amount,Quantity,Year,Month,Category
79594,2022-06,Alberta,"Milk, 2 litres",4.69,Dollars,Milk,2 litres,2 litres,2022,Jun,Dairy & Eggs
90046,2023-03,Quebec,"Oranges, per kilogram",6.46,Dollars,Oranges,per kilogram,1 kilogram,2023,Mar,Fruits & Vegetables
38280,2019-08,Manitoba,"Oranges, 1.36 kilograms",4.61,Dollars,Oranges,1.36 kilograms,1.36 kilograms,2019,Aug,Fruits & Vegetables
104609,2024-03,Quebec,"Infant formula, 900 grams",42.10,Dollars,Infant formula,900 grams,900 grams,2024,Mar,"Home,Beauty & Baby"
78670,2022-06,Canada,"Baby food, 128 millilitres",1.41,Dollars,Baby food,128 millilitres,128 millilitres,2022,Jun,"Home,Beauty & Baby"
85087,2022-11,New Brunswick,"Meatless burgers, 226 grams",5.97,Dollars,Meatless burgers,226 grams,226 grams,2022,Nov,Meat & Seafood
83757,2022-10,Nova Scotia,"Pork shoulder cuts, per kilogram",7.49,Dollars,Pork shoulder cuts,per kilogram,1 kilogram,2022,Oct,Meat & Seafood
35480,2019-06,Nova Scotia,"Canned tomatoes, 796 millilitres",1.56,Dollars,Canned tomatoes,796 millilitres,796 millilitres,2019,Jun,Pantry
49760,2020-06,Newfoundland and Labrador,"Vegetable oil, 3 litres",6.65,Dollars,Vegetable oil,3 litres,3 litres,2020,Jun,Pantry
38572,2019-08,Alberta,"Peanuts, 450 grams",3.48,Dollars,Peanuts,450 grams,450 grams,2019,Aug,Pantry

In [19]:
df.columns

Index(['REF_DATE', 'Location', 'Products', 'VALUE', 'UOM', 'Products Name',
       'Amount', 'Quantity', 'Year', 'Month', 'Category'],
      dtype='object')

In [20]:
df = df[['Year', 'Month','Location','Category','Products Name','Quantity','VALUE']]

In [21]:
df['Products Name'] = df['Products Name'].replace('Tea (20 bags)','Tea')
df['Quantity'] = df['Quantity'].fillna(' unit')

In [22]:
value = df['Quantity'].unique()
print(value)

<StringArray>
[      ' 1 kilogram',        ' 500 grams',        ' 400 grams',
        ' 300 grams',        ' 213 grams',        ' 170 grams',
        ' 226 grams',          ' 1 litre',         ' 2 litres',
         ' 4 litres',      ' 1.89 litres',        ' 454 grams',
        ' 907 grams',          ' 1 dozen',   ' 1.36 kilograms',
             ' unit',   ' 4.54 kilograms',        ' 227 grams',
        ' 142 grams',        ' 750 grams',       ' 750 grams ',
        ' 390 grams',        ' 600 grams',        ' 675 grams',
       ' 500 grams ',       ' 200 grams ',       ' 300 grams ',
       ' 900 grams ',      ' 2 kilograms',    ' 2.5 kilograms',
        ' 340 grams',         ' 3 litres',  ' 128 millilitres',
 ' 890 millilitres ',  ' 398 millilitres',  ' 796 millilitres',
  ' 284 millilitres',  ' 540 millilitres',  ' 341 millilitres',
        ' 900 grams',       ' 350 grams ',  ' 418 millilitres',
  ' 650 millilitres',  ' 475 millilitres',        ' 200 grams',
        ' 450 grams',       ' 400 grams ',         ' 85 grams',
  ' 100 millilitres',  ' 400 millilitres',      ' 4.43 litres']
Length: 51, dtype: string

In [23]:

df['Year'] = df['Year'].astype(int)
df.sample(10)

,Year,Month,Location,Category,Products Name,Quantity,VALUE
30447,2019,Feb,Prince Edward Island,Meat & Seafood,Beef rib cuts,1 kilogram,21.82
87475,2023,Jan,Nova Scotia,Pantry,Tofu,350 grams,2.58
18292,2018,Apr,Newfoundland and Labrador,Fruits & Vegetables,Onions,1.36 kilograms,3.54
75676,2022,Mar,Ontario,Fruits & Vegetables,Frozen green beans,750 grams,3.51
34223,2019,May,Nova Scotia,Fruits & Vegetables,Potatoes,1 kilogram,4.43
22680,2018,Jul,Saskatchewan,Fruits & Vegetables,Strawberries,454 grams,2.75
98707,2023,Oct,Manitoba,Meat & Seafood,Chicken breasts,1 kilogram,16.17
86547,2022,Dec,Ontario,Fruits & Vegetables,Celery,unit,3.65
19070,2018,Apr,Saskatchewan,Fruits & Vegetables,Squash,1 kilogram,3.17
43891,2020,Jan,Nova Scotia,Fruits & Vegetables,Cantaloupe,unit,3.18

In [24]:
df = df[df['Location']!='Canada']
df['Country'] = 'Canada'

In [25]:
df.head(10)

,Year,Month,Location,Category,Products Name,Quantity,VALUE,Country
110,2017,Jan,Newfoundland and Labrador,Meat & Seafood,Beef stewing cuts,1 kilogram,13.57,Canada
111,2017,Jan,Newfoundland and Labrador,Meat & Seafood,Beef striploin cuts,1 kilogram,16.51,Canada
112,2017,Jan,Newfoundland and Labrador,Meat & Seafood,Beef top sirloin cuts,1 kilogram,12.09,Canada
113,2017,Jan,Newfoundland and Labrador,Meat & Seafood,Beef rib cuts,1 kilogram,24.63,Canada
114,2017,Jan,Newfoundland and Labrador,Meat & Seafood,Ground beef,1 kilogram,8.13,Canada
115,2017,Jan,Newfoundland and Labrador,Meat & Seafood,Pork loin cuts,1 kilogram,5.92,Canada
116,2017,Jan,Newfoundland and Labrador,Meat & Seafood,Pork rib cuts,1 kilogram,5.88,Canada
117,2017,Jan,Newfoundland and Labrador,Meat & Seafood,Pork shoulder cuts,1 kilogram,6.01,Canada
118,2017,Jan,Newfoundland and Labrador,Meat & Seafood,Whole chicken,1 kilogram,5.76,Canada
119,2017,Jan,Newfoundland and Labrador,Meat & Seafood,Chicken breasts,1 kilogram,12.05,Canada

In [27]:
# Get the unique categories and locations in separate lists.
categories = df["Category"].unique()
Locations = df["Location"].unique()

print(categories)
print(Locations)
print(len(categories))
print(len(Locations))

['Meat & Seafood' 'Dairy & Eggs' 'Fruits & Vegetables' 'Pantry'
 'Home,Beauty & Baby']
['Newfoundland and Labrador' 'Prince Edward Island' 'Nova Scotia'
 'New Brunswick' 'Quebec' 'Ontario' 'Manitoba' 'Saskatchewan' 'Alberta'
 'British Columbia']
5
10

In [28]:
# Create numpy arrays from 1-6 for the categories and 1-12 for the locations
category_ids = np.arange(1, 6)
Locations_ids = np.arange(1, 11)
print(category_ids)
print(Locations_ids)

[1 2 3 4 5]
[ 1  2  3  4  5  6  7  8  9 10]

In [29]:
# Use a list comprehension to add "cat" to each category_id. 
cat_ids = ['cat' + str(each) for each in category_ids]
print(cat_ids)
# Use a list comprehension to add "subcat" to each subcategory_id.    
loc_ids = ['loc' + str(each) for each in Locations_ids]
print(loc_ids)

['cat1', 'cat2', 'cat3', 'cat4', 'cat5']
['loc1', 'loc2', 'loc3', 'loc4', 'loc5', 'loc6', 'loc7', 'loc8', 'loc9', 'loc10']

In [30]:
# Create a category DataFrame with the category_id array as the category_id and categories list as the category name.
category_df = pd.DataFrame({"category_id" : cat_ids , 'Category' : categories})
# Create a category DataFrame with the subcategory_id array as the subcategory_id and subcategories list as the subcategory name. 
Location_df = pd.DataFrame({"Location_id" : loc_ids , 'Location' : Locations})

In [31]:
category_df

  category_id             Category
0        cat1       Meat & Seafood
1        cat2         Dairy & Eggs
2        cat3  Fruits & Vegetables
3        cat4               Pantry
4        cat5   Home,Beauty & Baby

In [32]:
Location_df

  Location_id                   Location
0        loc1  Newfoundland and Labrador
1        loc2       Prince Edward Island
2        loc3                Nova Scotia
3        loc4              New Brunswick
4        loc5                     Quebec
5        loc6                    Ontario
6        loc7                   Manitoba
7        loc8               Saskatchewan
8        loc9                    Alberta
9       loc10           British Columbia

In [33]:
# Export  as CSV files.
category_df.to_csv("category.csv", index=False)

Location_df.to_csv("Locations.csv", index=False)

In [34]:
merged_df = pd.merge(df,category_df, on = 'Category' , how = 'left')
merged_df = pd.merge(merged_df,Location_df, on = 'Location' , how = 'left')
merged_df.head(10)

,Year,Month,Location,Category,Products Name,Quantity,VALUE,Country,category_id,Location_id
0,2017,Jan,Newfoundland and Labrador,Meat & Seafood,Beef stewing cuts,1 kilogram,13.57,Canada,cat1,loc1
1,2017,Jan,Newfoundland and Labrador,Meat & Seafood,Beef striploin cuts,1 kilogram,16.51,Canada,cat1,loc1
2,2017,Jan,Newfoundland and Labrador,Meat & Seafood,Beef top sirloin cuts,1 kilogram,12.09,Canada,cat1,loc1
3,2017,Jan,Newfoundland and Labrador,Meat & Seafood,Beef rib cuts,1 kilogram,24.63,Canada,cat1,loc1
4,2017,Jan,Newfoundland and Labrador,Meat & Seafood,Ground beef,1 kilogram,8.13,Canada,cat1,loc1
5,2017,Jan,Newfoundland and Labrador,Meat & Seafood,Pork loin cuts,1 kilogram,5.92,Canada,cat1,loc1
6,2017,Jan,Newfoundland and Labrador,Meat & Seafood,Pork rib cuts,1 kilogram,5.88,Canada,cat1,loc1
7,2017,Jan,Newfoundland and Labrador,Meat & Seafood,Pork shoulder cuts,1 kilogram,6.01,Canada,cat1,loc1
8,2017,Jan,Newfoundland and Labrador,Meat & Seafood,Whole chicken,1 kilogram,5.76,Canada,cat1,loc1
9,2017,Jan,Newfoundland and Labrador,Meat & Seafood,Chicken breasts,1 kilogram,12.05,Canada,cat1,loc1

In [35]:
merged_df.columns

Index(['Year', 'Month', 'Location', 'Category', 'Products Name', 'Quantity',
       'VALUE', 'Country', 'category_id', 'Location_id'],
      dtype='object')

In [36]:
merged_df= merged_df[['Year', 'Month','Country', 'Products Name', 'Quantity',
       'VALUE', 'category_id', 'Location_id']]

In [37]:
length_df = (len(merged_df))
print(length_df)

95613

In [38]:
# Create unique ids 
ID = np.arange(1, length_df + 1)
#primary_id = ['p_' + str(each) for each in ID]
#print(Rental_id)
merged_df["ID"] = ID

In [39]:
merged_df.columns

Index(['Year', 'Month', 'Country', 'Products Name', 'Quantity', 'VALUE',
       'category_id', 'Location_id', 'ID'],
      dtype='object')

In [40]:

merged_df =merged_df[['ID','Year', 'Month', 'Country','Products Name', 'Quantity', 'VALUE', 'category_id','Location_id']]
merged_df.sample(20)

,ID,Year,Month,Country,Products Name,Quantity,VALUE,category_id,Location_id
14323,14324,2018,Feb,Canada,Grapes,1 kilogram,6.68,cat3,loc1
61706,61707,2021,Sep,Canada,Romaine lettuce,unit,2.01,cat3,loc2
4704,4705,2017,May,Canada,Canned baked beans,398 millilitres,1.25,cat4,loc3
42201,42202,2020,Mar,Canada,Beef stewing cuts,1 kilogram,15.16,cat1,loc5
41139,41140,2020,Feb,Canada,Grapes,1 kilogram,5.77,cat3,loc5
73451,73452,2022,Jul,Canada,Cantaloupe,unit,4.09,cat3,loc9
95480,95481,2024,Mar,Canada,Peanut butter,1 kilogram,5.84,cat4,loc9
12291,12292,2017,Dec,Canada,Canned corn,341 millilitres,1.08,cat4,loc2
7855,7856,2017,Aug,Canada,Romaine lettuce,unit,1.64,cat3,loc2
67539,67540,2022,Feb,Canada,Frozen corn,750 grams,3.40,cat3,loc5
11332,11333,2017,Nov,Canada,Wieners,400 grams,2.98,cat1,loc4
28721,28722,2019,Mar,Canada,Cantaloupe,unit,3.33,cat3,loc2
56646,56647,2021,Apr,Canada,Onions,1.36 kilograms,3.82,cat3,loc6
77447,77448,2022,Nov,Canada,Orange juice,2 litres,4.00,cat4,loc5
29076,29077,2019,Mar,Canada,Frozen peas,750 grams,3.11,cat3,loc5
41860,41861,2020,Mar,Canada,Hummus,227 grams,3.53,cat4,loc1
80997,80998,2023,Feb,Canada,Beef striploin cuts,1 kilogram,20.88,cat1,loc8
63021,63022,2021,Oct,Canada,Celery,unit,2.72,cat3,loc4
41223,41224,2020,Feb,Canada,Chicken drumsticks,1 kilogram,7.29,cat1,loc6
36557,36558,2019,Oct,Canada,Dry or fresh pasta,500 grams,2.56,cat4,loc3

In [41]:
# Export the DataFrame as a CSV file. 
merged_df.to_csv("dataset.csv", index=False)